name    'counsyl-ruby'
version '0.9.9'
source  'git://github.com/counsyl/puppet-ruby.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Ruby language runtime and popular packages'
description 'Installs the Ruby language runtime and popular packages'
project_page 'https://github.com/counsyl/puppet-ruby'

dependency 'counsyl/sys', '>= 0.9.12'
